url: https://lai2023.github.io/
baseurl: 

# Site settings
title: LAI2023
email: lai23nitrkl@gmail.com
description: "Land-Atmosphere Interactions Controlling Weather & Climate: Applications of Numerical Models and Observations, 2023"


# Advisory committee names, titles and links
adv_com:

- name: Dr. Mrutyunjay Mohapatra
  pic: m_mohapatra
  position: DG, IMD

- name: Prof. U. C. Mohanty
  pic: uc_mohanty
  position: IIT Bhubaneswar

- name: Prof. A. P. Dimri
  pic: ap_dimri
  position: Director, IIG Mumbai

- name: Prof. S. Nautiyal
  pic: s_nautiyal
  position: Director, GBPNIHE Almora

- name: Dr. K. Kumar
  pic: k_kumar
  position: Nodal Officer, NMHS

- name: Prof. Subimal Ghosh
  pic: s_ghosh
  position: IIT Bombay

- name: Prof. A N V Satyanarayana
  pic: anv_satyanarayana
  position: IIT Kharagpur

- name: Prof. Ashok Karumuri
  pic: a_kurumuri
  position: Hyderabad Central University

# Program committee names, titles and links
prog_com:
- name: Prof. Sumit Sen
  pic: s_sen
  position: IIT Roorkee

- name: Dr. K. C. Sekar
  pic: kc_sekar
  position: GBPNIHE

- name: Dr. Sandipan Mukherjee
  pic: s_mukherjee
  position: Sc-D, GBPNIHE

- name: Dr. Vaibhav Gosavi
  pic: v_gosavi
  position: Sc-C, GBPNIHE

- name: 
  pic: 
  position: 

- name: Dr. Krishna Kishore Osuri
  pic: kk_osuri
  position: NIT Rourkela

- name: Dr. Jagabandhu Panda
  pic: j_panda
  position: NIT Rourkela

# Patron names, titles and links
patron:
- name: 
  pic: 
  position: 

- name: Prof. K .Umamaheshwar Rao
  pic: ku_rao
  position: Director, NIT Rourkela

# Convener names, titles and links
convener:
- name: 
  pic: 
  position: 
  
- name: Dr. Krishna Kishore Osuri
  pic: kk_osuri
  position: NIT Rourkela

# Co-converner names, titles and links
co-convener:
- name: 
  pic: 
  position: 
  
- name: Dr. Jagabandhu Panda
  pic: j_panda
  position: NIT Rourkela

- name: Dr. Sandipan Mukherjee
  pic: s_mukherjee
  position: GBPNIHE

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://lai2023.github.io/

# Postal address (add as many lines as necessary)
address:
  - line: Department of Earth and Atmospheric Sciences
  - line: National Institute of Technology Rourkela
  - line: Rourkela, Odisha
  - line: PIN 769008

# Build settings
markdown: kramdown
permalink: pretty